name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight
  workflow_dispatch: # Allow manual triggering
  push:
    branches:
      - main # Or your default branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for the snake generation

      - name: Generate snake
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: casiendetra # Replace with your GitHub username
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output # This will create/update the 'output' branch
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
